---
  - hosts: all
    become: yes
    roles:
      - geerlingguy.docker
    vars:
      docker_user: 'homeadmin'
    tasks:
      - name: add homeadmin to docker group
        ansible.builtin.user:
          name: '{{ docker_user }}'
          groups: docker
          append: true


  - hosts: netbox
    tasks:
      - name: import netbox tasks
        ansible.builtin.import_tasks:
          file: tasks/netbox.yml
  - hosts: zabbix
    tasks:
      - name: import zabbix tasks
        ansible.builtin.import_tasks:
          file: tasks/zabbix.yml
